server:
  port: ${SERVER_PORT:8082}
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  data:
    rest:
      detection-strategy: annotated

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
          default_batch_fetch_size: 50
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
    drop-first: false


  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOST_NAME:localhost:9093}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      bootstrap-servers: ${KAFKA_HOST_NAME:localhost:9093}
      group-id: orders
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

kafka:
  candle-stream-topic: ${CANDLE_STREAM_TOPIC:CandleStreamTopic}
