export const GET_DATA_FAILURE = "GET_DATA_FAILURE";
export const GET_DATA_STARTED = "GET_DATA_STARTED";
export const GET_COINS_SUCCESS = "GET_COINS_SUCCESS";
<<<<<<< HEAD
export const GET_SEARCH_COINS_SUCCESS = "GET_SEARCH_COINS_SUCCESS";

export const GET_COIN_CHART_INFO_SUCCESS = "GET_COIN_CHART_INFO_SUCCESS";

export const GET_CRYPTO_CANDLE_RANGE_SUCCESS =
  "GET_CRYPTO_CANDLE_RANGE_SUCCESS";
=======

export const GET_SEARCH_COINS_SUCCESS = "GET_SEARCH_COINS_SUCCESS";

export const GET_CRYPTO_CANDLE_RANGE_SUCCESS =
  "GET_CRYPTO_CANDLE_RANGE_SUCCESS";

>>>>>>> 1fa2e89d771cc802b3f4a86fd5b779c7e63dfad2

export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_STARTED = "AUTH_STARTED";

export const REGISTRATION_SUCCESS = "REGISTRATION _SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

<<<<<<< HEAD
export const LOGOUT = "LOGOUT";

export const SAVE_CURRENT_CRYPTO = "SAVE_CURRENT_CRYPTO";
=======

export const LOGOUT = "LOGOUT";
n
>>>>>>> 1fa2e89d771cc802b3f4a86fd5b779c7e63dfad2
