export const GET_DATA_FAILURE = "GET_DATA_FAILURE";
export const GET_DATA_STARTED = "GET_DATA_STARTED";
export const GET_COINS_SUCCESS = "GET_COINS_SUCCESS";

export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_STARTED = "AUTH_STARTED";

export const REGISTRATION_SUCCESS = "REGISTRATION _SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
